spring:
  ai:
    model:
      chat: openai
      embedding: openai
    openai:
      base-url: ${OPENAI_BASE_URL:ttps://openrouter.ai/api/v1}
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: ${OPENAI_CHAT_MODEL:anthropic/claude-3-haiku}
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL:text-embedding-3-small}
          encoding-format: float
    vectorstore:
      pgvector:
        dimensions: ${EMBEDDING_DIMENSIONS:3072}
